# Generated by Django 2.2.4 on 2021-03-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200510_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
