# Generated by Django 2.2.4 on 2021-03-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
    ]
